
modLoader="javafml"
loaderVersion="47,)"
license="All rights reserved"
[[mods]]
modId="bettas"
version="1.2.1"
displayName="DragN's Bettas"
logoFile="temp.png"
credits="EvangeliX, Code. DragN0007, Assets"
authors="DragN0007, EvangeliX"
description='''
Bettas & Aquatics is a small mod that aims to add cute bettas & other fish to your game. Find the betta biome and browse through over 3400 betta types for your perfect color and pattern scheme for your new aquarium!
'''
[[dependencies.bettas]]
    modId="forge"
    mandatory=true
    versionRange="47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bettas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.bettas]]
    modId="geckolib"
    mandatory=true
    versionRange = "[4.4.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bettas]]
    modId="terrablender"
    mandatory=true
    versionRange="[3.0.1.4,)"
    ordering="NONE"
    side="BOTH"